/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package p2lab7_gabrielzelaya;

/**
 *
 * @author gabri
 */
public class GoogleUndead extends javax.swing.JFrame {

    /**
     * Creates new form GoogleUndead
     */
    public GoogleUndead() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        barra_izquierda = new javax.swing.JPanel();
        btn_destacados = new javax.swing.JPanel();
        txt_destacados = new javax.swing.JLabel();
        btn_miUnidad = new javax.swing.JPanel();
        txt_miUnidad = new javax.swing.JLabel();
        btn_papelera = new javax.swing.JPanel();
        txt_papelera = new javax.swing.JLabel();
        bg_miUnidad = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        miUnidad_tree = new javax.swing.JTree();
        bg_destacados = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        destacados_tree = new javax.swing.JTree();
        bg_papelera = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        papelera_tree = new javax.swing.JTree();
        bg_descarga = new javax.swing.JPanel();
        pbar_descarga = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("googleUndead");
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        barra_izquierda.setBackground(new java.awt.Color(255, 255, 255));
        barra_izquierda.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_destacados.setBackground(new java.awt.Color(255, 255, 255));

        txt_destacados.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        txt_destacados.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_destacados.setText("Destacados");

        javax.swing.GroupLayout btn_destacadosLayout = new javax.swing.GroupLayout(btn_destacados);
        btn_destacados.setLayout(btn_destacadosLayout);
        btn_destacadosLayout.setHorizontalGroup(
            btn_destacadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txt_destacados, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
        );
        btn_destacadosLayout.setVerticalGroup(
            btn_destacadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txt_destacados, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        barra_izquierda.add(btn_destacados, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 220, 50));

        btn_miUnidad.setBackground(new java.awt.Color(255, 255, 255));
        btn_miUnidad.setPreferredSize(new java.awt.Dimension(181, 55));

        txt_miUnidad.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        txt_miUnidad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_miUnidad.setText("Mi Unidad");

        javax.swing.GroupLayout btn_miUnidadLayout = new javax.swing.GroupLayout(btn_miUnidad);
        btn_miUnidad.setLayout(btn_miUnidadLayout);
        btn_miUnidadLayout.setHorizontalGroup(
            btn_miUnidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txt_miUnidad, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
        );
        btn_miUnidadLayout.setVerticalGroup(
            btn_miUnidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txt_miUnidad, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
        );

        barra_izquierda.add(btn_miUnidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 71, 220, -1));

        btn_papelera.setBackground(new java.awt.Color(255, 255, 255));
        btn_papelera.setPreferredSize(new java.awt.Dimension(181, 55));

        txt_papelera.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        txt_papelera.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_papelera.setText("Papelera");

        javax.swing.GroupLayout btn_papeleraLayout = new javax.swing.GroupLayout(btn_papelera);
        btn_papelera.setLayout(btn_papeleraLayout);
        btn_papeleraLayout.setHorizontalGroup(
            btn_papeleraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txt_papelera, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
        );
        btn_papeleraLayout.setVerticalGroup(
            btn_papeleraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txt_papelera, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
        );

        barra_izquierda.add(btn_papelera, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 220, -1));

        getContentPane().add(barra_izquierda, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 545));

        bg_miUnidad.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Mi Unidad");
        miUnidad_tree.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane1.setViewportView(miUnidad_tree);

        javax.swing.GroupLayout bg_miUnidadLayout = new javax.swing.GroupLayout(bg_miUnidad);
        bg_miUnidad.setLayout(bg_miUnidadLayout);
        bg_miUnidadLayout.setHorizontalGroup(
            bg_miUnidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bg_miUnidadLayout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
        );
        bg_miUnidadLayout.setVerticalGroup(
            bg_miUnidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bg_miUnidadLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        getContentPane().add(bg_miUnidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 580, 470));

        bg_destacados.setBackground(new java.awt.Color(255, 255, 255));

        destacados_tree.setPreferredSize(new java.awt.Dimension(84, 20));
        jScrollPane2.setViewportView(destacados_tree);

        javax.swing.GroupLayout bg_destacadosLayout = new javax.swing.GroupLayout(bg_destacados);
        bg_destacados.setLayout(bg_destacadosLayout);
        bg_destacadosLayout.setHorizontalGroup(
            bg_destacadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bg_destacadosLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );
        bg_destacadosLayout.setVerticalGroup(
            bg_destacadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bg_destacadosLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        getContentPane().add(bg_destacados, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 580, 470));

        bg_papelera.setBackground(new java.awt.Color(255, 255, 255));

        papelera_tree.setPreferredSize(new java.awt.Dimension(84, 20));
        jScrollPane3.setViewportView(papelera_tree);

        javax.swing.GroupLayout bg_papeleraLayout = new javax.swing.GroupLayout(bg_papelera);
        bg_papelera.setLayout(bg_papeleraLayout);
        bg_papeleraLayout.setHorizontalGroup(
            bg_papeleraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bg_papeleraLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );
        bg_papeleraLayout.setVerticalGroup(
            bg_papeleraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bg_papeleraLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        getContentPane().add(bg_papelera, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 580, 470));

        bg_descarga.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout bg_descargaLayout = new javax.swing.GroupLayout(bg_descarga);
        bg_descarga.setLayout(bg_descargaLayout);
        bg_descargaLayout.setHorizontalGroup(
            bg_descargaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 580, Short.MAX_VALUE)
            .addGroup(bg_descargaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(bg_descargaLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pbar_descarga, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        bg_descargaLayout.setVerticalGroup(
            bg_descargaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
            .addGroup(bg_descargaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(bg_descargaLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pbar_descarga, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        getContentPane().add(bg_descarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 580, 80));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GoogleUndead.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GoogleUndead.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GoogleUndead.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GoogleUndead.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GoogleUndead().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel barra_izquierda;
    private javax.swing.JPanel bg_descarga;
    private javax.swing.JPanel bg_destacados;
    private javax.swing.JPanel bg_miUnidad;
    private javax.swing.JPanel bg_papelera;
    private javax.swing.JPanel btn_destacados;
    private javax.swing.JPanel btn_miUnidad;
    private javax.swing.JPanel btn_papelera;
    private javax.swing.JTree destacados_tree;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTree miUnidad_tree;
    private javax.swing.JTree papelera_tree;
    private javax.swing.JProgressBar pbar_descarga;
    private javax.swing.JLabel txt_destacados;
    private javax.swing.JLabel txt_miUnidad;
    private javax.swing.JLabel txt_papelera;
    // End of variables declaration//GEN-END:variables
}
